# Config file for automatic testing at travis-ci.org

language: python
python: 3.6
cache: pip

env:
  global:
    - SOLC_URL='https://github.com/ethereum/solidity/releases/download/v0.4.23/solc-static-linux'
    - SOLC_VERSION='v0.4.23'

before_install:
  - mkdir -p $HOME/.bin
  - export PATH=$PATH:$HOME/.bin
  - ./.travis/download_solc.sh

install: pip install -r requirements-dev.txt

script:
  - make lint
  - make typecheck
  - make test
